#!/usr/bin/env bash

if [[ $1 == false ]]; then
    echo "usage: create-module <module-name>"
    exit 1
fi

mkdir lib/$1
mkdir lib/$1/obj
cp ./templates/makefile-template lib/$1/makefile
cp ./templates/module-template lib/$1/interface.h
touch lib/$1/implementation.c

echo "MODULE lib/$1 created"
echo "check new files for due configuration..."
