#!/usr/bin/env perl

use List::Util qw(min);

@commands = `cat makefile | grep '[a-z]:' | awk '{ print $1 }'`;
@documentation = `cat makefile | grep "^#@" | tr -d "#@"`;

print " usage: make <command>\n\n";

$length = min((scalar @commands), (scalar @documentation)) - 1;

for (0..$length) {
    printf(" %s\t%s\n", @commands[$_], @documentation[$_]);
}
